In [16]:
#Dependencies

import pandas as pd
from sqlalchemy import create_engine
from flask import Flask, render_template, redirect,jsonify

In [17]:
# Extract "dictionary.csv" file to datafreame

csv_file = "data/Full Data Set with Definitions.csv"
dictionary_df = pd.read_csv(csv_file)
dictionary_df.head()

,Layer,Name,GEOID,Longitude,Latitude,HCSDIAP_2016-2018,VRDIAR_2015-2019,VRDIBR_2015-2019,VRCAR_2015-2019,VRADR_2015-2019,...,PCT-W_2015-2019,PCT-B_2015-2019,PCT-A_2015-2019,PCT-H_2015-2019,POP_2015-2019,POP-I_2015-2019,POP-J_2015-2019,POP-Y_2015-2019,POP-O_2015-2019,POP-S_2015-2019
0,Community area,Rogers Park,1,-87.670171,42.009630,11.2,29.3,78.6,186.2,25.2,...,43.965183,26.130150,5.132455,20.635640,52553.20678,3124.390755,6678.308255,21570.203660,16430.330990,4749.973126
1,Community area,Norwood Park,10,-87.803451,41.985248,9.3,18.1,48.2,169.0,36.0,...,77.986018,0.822230,4.232331,14.108420,38676.02969,2368.615994,5266.524349,10339.697910,13210.135000,7491.056443
2,Community area,Jefferson Park,11,-87.771165,41.978836,9.8,11.0,37.9,169.1,15.1,...,63.127919,1.018366,8.970529,24.335807,27475.35983,1706.307244,3913.687375,8049.428085,9402.435270,4403.501859
3,Community area,Forest Glen,12,-87.758358,41.993938,NaN,5.6,27.5,142.8,22.1,...,72.726359,1.266395,9.213158,14.284026,19361.55814,1300.748710,3603.149463,4134.884681,6765.473444,3557.301842
4,Community area,North Park,13,-87.723578,41.983651,17.3,27.4,62.2,133.3,16.3,...,51.134413,2.181057,22.713717,20.410985,18896.62848,1432.360534,2841.161052,5488.673648,5390.274835,3744.158407

In [18]:
dictionary_df.columns

Index(['Layer', 'Name', 'GEOID', 'Longitude', 'Latitude', 'HCSDIAP_2016-2018',
       'VRDIAR_2015-2019', 'VRDIBR_2015-2019', 'VRCAR_2015-2019',
       'VRADR_2015-2019', 'HCSHYTP_2016-2018', 'HCSOBP_2016-2018',
       'VRCHDR_2015-2019', 'HCSPAP_2016-2018', 'HCSSP_2016-2018',
       'HCSRCP_2016-2018', 'HCSSMKP_2016-2018', 'HCSBDP_2016-2018',
       'HCSFVP_2016-2018', 'HCSFVAP_2016-2018', 'LFA_2019', 'PMC_2020',
       'UNS_2015-2019', 'HDX_2015-2019', 'VRLE_2019', 'HCSNCP_2016-2018',
       'VRBWP_2013-2017', 'HCSOHSP_2016-2018', 'INC_2015-2019',
       'POV_2015-2019', 'SNP_2015-2019', 'TNF_2015-2019', 'EDB_2015-2019',
       'EDE_2015-2019', 'PCT-F_2015-2019', 'PCT-W_2015-2019',
       'PCT-B_2015-2019', 'PCT-A_2015-2019', 'PCT-H_2015-2019',
       'POP_2015-2019', 'POP-I_2015-2019', 'POP-J_2015-2019',
       'POP-Y_2015-2019', 'POP-O_2015-2019', 'POP-S_2015-2019'],
      dtype='object')

In [19]:
dictionary_df.rename(columns={"VRDIBR_2015-2019":"VRDIBR_2015_2019","VRDIAR_2015-2018":"VRDIAR_2015_2018","VRDTH_2015-2019":"VRDTH_2015_2019","VRCAR_2015-2019":"VRCAR_2015_2019","VRADR_2015-2019":"VRADR_2015_2019","HCSHYTP_2016-2018":"HCSHYTP_2016_2018","HCSOBP_2016-2018":"HCSOBP_2016_2018","VRCHDR_2015-2019":"VRCHDR_2015_2019","HDX_2015-2019":"HDX_2015_2019"},inplace=True)

dictionary_df

,Layer,Name,GEOID,Longitude,Latitude,HCSDIAP_2016-2018,VRDIAR_2015-2019,VRDIBR_2015_2019,VRCAR_2015_2019,VRADR_2015_2019,...,PCT-W_2015-2019,PCT-B_2015-2019,PCT-A_2015-2019,PCT-H_2015-2019,POP_2015-2019,POP-I_2015-2019,POP-J_2015-2019,POP-Y_2015-2019,POP-O_2015-2019,POP-S_2015-2019
0,Community area,Rogers Park,1,-87.670171,42.009630,11.2,29.3,78.6,186.2,25.2,...,43.965183,26.130150,5.132455,20.635640,52553.20678,3124.390755,6678.308255,21570.203660,16430.330990,4749.973126
1,Community area,Norwood Park,10,-87.803451,41.985248,9.3,18.1,48.2,169.0,36.0,...,77.986018,0.822230,4.232331,14.108420,38676.02969,2368.615994,5266.524349,10339.697910,13210.135000,7491.056443
2,Community area,Jefferson Park,11,-87.771165,41.978836,9.8,11.0,37.9,169.1,15.1,...,63.127919,1.018366,8.970529,24.335807,27475.35983,1706.307244,3913.687375,8049.428085,9402.435270,4403.501859
3,Community area,Forest Glen,12,-87.758358,41.993938,NaN,5.6,27.5,142.8,22.1,...,72.726359,1.266395,9.213158,14.284026,19361.55814,1300.748710,3603.149463,4134.884681,6765.473444,3557.301842
4,Community area,North Park,13,-87.723578,41.983651,17.3,27.4,62.2,133.3,16.3,...,51.134413,2.181057,22.713717,20.410985,18896.62848,1432.360534,2841.161052,5488.673648,5390.274835,3744.158407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Community area,Morgan Park,75,-87.669062,41.689729,13.2,23.3,61.2,198.4,38.5,...,27.811319,63.869498,0.274963,5.265582,21594.81594,1189.782263,3613.802519,5113.302163,7681.268866,3996.660127
73,Community area,O'Hare,76,-87.893699,41.975696,NaN,14.9,35.5,180.8,10.6,...,63.025165,1.843656,4.382254,29.909154,15655.21018,1159.729352,1616.185515,5802.300811,4710.727015,2366.267487
74,Community area,Edgewater,77,-87.663419,41.986719,9.8,19.1,50.6,158.7,18.5,...,60.481699,9.997478,10.509129,15.540250,48691.02556,1877.377542,3498.895647,20119.025990,15648.268120,7547.458257
75,Community area,Near North Side,8,-87.633318,41.899611,4.1,8.2,22.6,143.7,17.8,...,67.583980,10.676831,12.132734,6.999336,84576.02433,3257.400822,3145.387457,43140.429900,21335.985490,13696.820670
76,Community area,Edison Park,9,-87.813780,42.007627,NaN,6.8,23.5,117.1,15.2,...,83.513288,0.365507,3.410075,9.728615,11254.80280,825.142461,1590.782999,2881.178697,4120.859646,1836.838995

In [20]:
dictionary_df.rename(columns = {"INC_2015-2019":"Median_Household_Income","POV_2015-2019":"Poverty_Rate","SNP_2015-2019":"Receiving_Food_Stamps","TNF_2015-2019":"Public_Assistance_Income","EDB_2015-2019":"High_School_Grad_Rate","EDE_2015-2019":"College_Grad_Rate"},inplace = True)

In [21]:
dictionary_df.rename(columns = {"PCT-W_2015-2019":"Non_Hispanic_White","PCT-B_2015_2019":"Non_Hispanic_Black","PCT-A_2015-2019":"Asian_Pacific_Islander","PCT-H_2015-2019":"Hispanic_or_Latino","POP-I_2015-2019":"Population_Infants","POP-J_2015-2019":"Population_Juveniles","POP-Y_2015-2019":"Population_Young_Adults","POP-O_2015-2019":"Population_Middle_Aged_Adults","POP-S_2015-2019":"Population_Seniors"},inplace = True)

In [22]:
dictionary_df.rename(columns = {"PCT-B_2015-2019":"Non_Hispanic_Black"},inplace = True)

In [23]:
dictionary_df.columns

Index(['Layer', 'Name', 'GEOID', 'Longitude', 'Latitude', 'HCSDIAP_2016-2018',
       'VRDIAR_2015-2019', 'VRDIBR_2015_2019', 'VRCAR_2015_2019',
       'VRADR_2015_2019', 'HCSHYTP_2016_2018', 'HCSOBP_2016_2018',
       'VRCHDR_2015_2019', 'HCSPAP_2016-2018', 'HCSSP_2016-2018',
       'HCSRCP_2016-2018', 'HCSSMKP_2016-2018', 'HCSBDP_2016-2018',
       'HCSFVP_2016-2018', 'HCSFVAP_2016-2018', 'LFA_2019', 'PMC_2020',
       'UNS_2015-2019', 'HDX_2015_2019', 'VRLE_2019', 'HCSNCP_2016-2018',
       'VRBWP_2013-2017', 'HCSOHSP_2016-2018', 'Median_Household_Income',
       'Poverty_Rate', 'Receiving_Food_Stamps', 'Public_Assistance_Income',
       'High_School_Grad_Rate', 'College_Grad_Rate', 'PCT-F_2015-2019',
       'Non_Hispanic_White', 'Non_Hispanic_Black', 'Asian_Pacific_Islander',
       'Hispanic_or_Latino', 'POP_2015-2019', 'Population_Infants',
       'Population_Juveniles', 'Population_Young_Adults',
       'Population_Middle_Aged_Adults', 'Population_Seniors'],
      dtype='object')

In [24]:
engine = create_engine('sqlite:///data/mydatabase.db')

In [ ]:
#"data cleaning and processing"

In [25]:
dictionary_df.to_sql('healthatlas',engine,if_exists='replace')

In [26]:
pd.read_sql_query('select * from healthatlas', con=engine).head()

,index,Layer,Name,GEOID,Longitude,Latitude,HCSDIAP_2016-2018,VRDIAR_2015-2019,VRDIBR_2015_2019,VRCAR_2015_2019,...,Non_Hispanic_White,Non_Hispanic_Black,Asian_Pacific_Islander,Hispanic_or_Latino,POP_2015-2019,Population_Infants,Population_Juveniles,Population_Young_Adults,Population_Middle_Aged_Adults,Population_Seniors
0,0,Community area,Rogers Park,1,-87.670171,42.009630,11.2,29.3,78.6,186.2,...,43.965183,26.130150,5.132455,20.635640,52553.20678,3124.390755,6678.308255,21570.203660,16430.330990,4749.973126
1,1,Community area,Norwood Park,10,-87.803451,41.985248,9.3,18.1,48.2,169.0,...,77.986018,0.822230,4.232331,14.108420,38676.02969,2368.615994,5266.524349,10339.697910,13210.135000,7491.056443
2,2,Community area,Jefferson Park,11,-87.771165,41.978836,9.8,11.0,37.9,169.1,...,63.127919,1.018366,8.970529,24.335807,27475.35983,1706.307244,3913.687375,8049.428085,9402.435270,4403.501859
3,3,Community area,Forest Glen,12,-87.758358,41.993938,NaN,5.6,27.5,142.8,...,72.726359,1.266395,9.213158,14.284026,19361.55814,1300.748710,3603.149463,4134.884681,6765.473444,3557.301842
4,4,Community area,North Park,13,-87.723578,41.983651,17.3,27.4,62.2,133.3,...,51.134413,2.181057,22.713717,20.410985,18896.62848,1432.360534,2841.161052,5488.673648,5390.274835,3744.158407